// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx0DhM0gDm4c3AfVKNApvd2TouWY8_e_U',
    appId: '1:166719206090:web:e4b5c4ffb3c3fad8d17a33',
    messagingSenderId: '166719206090',
    projectId: 'wygs-app',
    authDomain: 'wygs-app.firebaseapp.com',
    storageBucket: 'wygs-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiZYH3jD52SsZinfQ2oTOq4JDLoIasAKw',
    appId: '1:166719206090:android:48ba962a7ffd5068d17a33',
    messagingSenderId: '166719206090',
    projectId: 'wygs-app',
    storageBucket: 'wygs-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWHAxaerjzhW5Yjs4nmatPoWh6WgabjDU',
    appId: '1:166719206090:ios:84247e226cbe8d9fd17a33',
    messagingSenderId: '166719206090',
    projectId: 'wygs-app',
    storageBucket: 'wygs-app.appspot.com',
    iosBundleId: 'wygs.com.wygs.guitarSongs',
  );
}
